mod_kwargs:
  fc_hidden_dim: 64
  hidden_channels: 10
  in_channels: 1
  num_blks: 2
  num_classes: 10
  num_convs: 2
train_kwargs:
  batch_size: 100
  learning_rate: 0.001
  min_delta: 0.0005
  num_epochs: 50
  num_workers: 0
  patience: 15
